### PR TITLE
Submission of Local Linearity Regularizer + Adversarially Trained model

### PR DESCRIPTION
**Pull request by emmyqin**
This is a submission for the unrestricted adversarial challenge: Phase I. The entry is uses a pre-trained ImageNet model with Local Linearity Regularizer, then adversarially trained using birds-or-bicycles dataset (train and extras) as provided by the challenge.

### CODE REVIEW

**Comment by nottombrown** [comment]
This looks good to me. Thanks for the link to a github repo that's clear and easy to execute
https://github.com/deepmind/deepmind-research/tree/master/unrestricted_advx

I'd like to merge this in, but it looks like the python 3.5 tests are bitrotten, and since I've left Google, I no longer have admin access to disable 3.5 tests so that this could be merged.

@carlini, would you be up to do the following?

1) Disable the bitrotten python 3.5 travis tests (but leave 2.7 intact)
2) Either merge this in, or give me write-access so that I can merge things in the future (if that is easy)

Thanks!

**Comment by carlini** [comment]
Sorry for the delay on this. Tom you should have had access--not sure why you didn't, you do now.

Do we want to remove the 3.5 tests or should we fix them?

**Comment by juesato** [comment]
Commenting so that Github know to notify me about new comments.

**Comment by juesato** [comment]
Hi @nottombrown , are you able to merge this now?

**Comment by nottombrown** [comment]
Merged! Thanks for you patience @juesato and @emmyqin

**Comment by nottombrown** [comment]
@carlini - I'll remove the bitrotten 3.5 test for now and will accept PRs to fix them

**Pull request merged**
