### PR TITLE
Simple Parallel Spatial Attack

### PR DESCRIPTION
**Pull request by nottombrown**
This is a simple spatial attack that just uses multiprocessing to generate candidate attacks. It will use all the available CPUs.

Profiling the attack, we find that it is CPU bound even when we have a machine with 32 available CPUs and a single P100 GPU.

(`run_attack` contains the GPU work)
image

After optimizing, the attack takes ~45 minutes to run on the keras model and ~30 minutes to run on the pytorch model

### CODE REVIEW

**Comment by nottombrown** [comment]
@carlini - Could you take a look at this? It uses just `np` because `tf` is hard to profile / optimize when doing multiprocessing. I plan to remove all the other implementations of the spatial attack and just use this.

I removed the `valid_check` feature, because I wasn't certain that it was necessary. If you think that it's important then I can add it back.

**Comment by carlini** [comment]
`valid_check` is important for MNIST. Otherwise you end up clipping the entire digit outside of the bounding box.

**Comment by nottombrown** [comment]
Ok, I’ll add it back tomorrow.

**Comment by nottombrown** [comment]
Added back the MNIST check. Currently we still have two versions, but we can deprecate the old one at a later date.

Here are some sampled incorrectly classified images that the attack found on the keras resnet:
image
image
image
image

**Pull request merged**
